// IRON RULE: make test-full must always be able to run simultaneously in the
// same repository without conflicting. Nothing else matters more than this.

package systemcontroller

import (
	"context"
	"errors"
	"testing"

	"gitea.com/town-os/town-os/src/monitoring"
	"gitea.com/town-os/town-os/src/storage"
	"gitea.com/town-os/town-os/src/systemd"
)

func initSystemServiceTestClient(t *testing.T) (*SystemdClient, *systemd.MockManager) {
	t.Helper()
	mock := storage.InitBtrFSMock()
	sd := systemd.InitMockManager()

	ts := InitTestServer(ServerConfig{
		Storage:                    mock,
		Systemd:                    sd,
		MonitoringBackend:          monitoring.BackendUPlot,
		SystemControllerImage:      "quay.io/town/town:test",
		SystemControllerListenAddr: ":5309",
	})
	t.Cleanup(ts.Close)

	c, err := ts.Client()
	if err != nil {
		t.Fatalf("ts.Client: %v", err)
	}

	return c, sd
}

func TestHTTPListSystemServicesWithoutMonitoring(t *testing.T) {
	mock := storage.InitBtrFSMock()
	ts := InitTestServer(ServerConfig{Storage: mock})
	t.Cleanup(ts.Close)

	c, err := ts.Client()
	if err != nil {
		t.Fatalf("ts.Client: %v", err)
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 0 {
		t.Fatalf("expected 0 entries without monitoring, got %d", len(entries))
	}
}

func TestHTTPListSystemServicesWithMonitoring(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	// Monitoring services (node-exporter, prometheus, monitoring-ui) plus
	// the systemcontroller itself.
	if len(entries) != 4 {
		t.Fatalf("expected 4 entries (node-exporter, prometheus, monitoring-ui, systemcontroller), got %d", len(entries))
	}

	keys := map[string]bool{}
	for _, e := range entries {
		keys[e.Key] = true
		if e.Image == "" {
			t.Fatalf("expected non-empty image for %s", e.Key)
		}
		if e.Port == "" {
			t.Fatalf("expected non-empty port for %s", e.Key)
		}
		if e.DisplayName == "" {
			t.Fatalf("expected non-empty display name for %s", e.Key)
		}
	}

	for _, expected := range []string{"node-exporter", "prometheus", "monitoring-ui", SystemControllerServiceKey} {
		if !keys[expected] {
			t.Fatalf("expected key %q in system services", expected)
		}
	}
}

func TestHTTPListSystemServicesReportsRunningState(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active", SubState: "running"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active", SubState: "running"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active", SubState: "running"},
		{Name: systemd.SystemControllerUnitName, ActiveState: "active", SubState: "running"},
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 4 {
		t.Fatalf("expected 4 entries, got %d", len(entries))
	}

	for _, e := range entries {
		if e.ActiveState != "active" {
			t.Fatalf("expected %s active, got %q", e.Key, e.ActiveState)
		}
	}
}

// TestHTTPListSystemServicesIgnoresNCAndSocketUnits verifies that system
// service NC and socket units (generated by the package unit path for
// monitoring services) are not returned as separate entries from
// ListSystemServices — only the main service entries are returned.
func TestHTTPListSystemServicesIgnoresNCAndSocketUnits(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active"},
		{Name: "town-os-system--prometheus-network.service", ActiveState: "active"},
		{Name: "town-os-system--prometheus-9090-tcp.socket", ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-network.service", ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-5308-tcp.socket", ActiveState: "active"},
		{Name: systemd.SystemControllerUnitName, ActiveState: "active"},
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 4 {
		t.Fatalf("expected 4 entries (NC and socket units excluded), got %d", len(entries))
	}
	for _, e := range entries {
		switch e.Key {
		case "node-exporter", "prometheus", "monitoring-ui", SystemControllerServiceKey:
			// ok
		default:
			t.Fatalf("unexpected entry key %q", e.Key)
		}
	}
}

func TestHTTPSetSystemServiceStatusStart(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	if err := c.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Start); err != nil {
		t.Fatalf("SetSystemServiceStatus: %v", err)
	}

	calls := sd.GetCalls()
	found := false
	for _, call := range calls {
		if call.Method == "SetStatus" && len(call.Args) >= 2 {
			if call.Args[0] == systemd.SystemServiceUnitName("node-exporter") && call.Args[1] == systemd.Start {
				found = true
			}
		}
	}
	if !found {
		t.Fatal("expected SetStatus(node-exporter, start) call")
	}
}

func TestHTTPSetSystemServiceStatusRestart(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	if err := c.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Restart); err != nil {
		t.Fatalf("SetSystemServiceStatus: %v", err)
	}
}

func TestHTTPSetSystemServiceStatusEnableRejected(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	err := c.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Enable)
	if err == nil {
		t.Fatal("expected error for enable action")
	}
}

func TestHTTPSetSystemServiceStatusInvalidKey(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	err := c.SetSystemServiceStatus(context.TODO(), "nonexistent", systemd.Start)
	if err == nil {
		t.Fatal("expected error for invalid key")
	}
}

func TestHTTPPingIncludesSystemServiceCounts(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active"},
		{Name: systemd.SystemControllerUnitName, ActiveState: "active"},
	}

	ping, err := c.Ping(context.TODO())
	if err != nil {
		t.Fatalf("Ping: %v", err)
	}

	if ping.SystemServices == nil {
		t.Fatal("expected system_services in ping response")
	}

	if ping.SystemServices.Total != 4 {
		t.Fatalf("expected 4 total system services, got %d", ping.SystemServices.Total)
	}

	if ping.SystemServices.Active != 4 {
		t.Fatalf("expected 4 active system services, got %d", ping.SystemServices.Active)
	}
}

// TestHTTPPingExcludesSystemServiceNCAndSocketUnits verifies that network
// controller and socket units generated for system services (via the package
// unit path for prometheus, monitoring-ui, etc.) are not counted in the
// system_services total — only the main service units are.
func TestHTTPPingExcludesSystemServiceNCAndSocketUnits(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active"},
		{Name: "town-os-system--prometheus-network.service", ActiveState: "active"},
		{Name: "town-os-system--prometheus-9090-tcp.socket", ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-network.service", ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-5308-tcp.socket", ActiveState: "active"},
		{Name: systemd.SystemControllerUnitName, ActiveState: "active"},
	}

	ping, err := c.Ping(context.TODO())
	if err != nil {
		t.Fatalf("Ping: %v", err)
	}

	if ping.SystemServices == nil {
		t.Fatal("expected system_services in ping response")
	}

	// node-exporter, prometheus, monitoring-ui, systemcontroller — no NC or sockets.
	if ping.SystemServices.Total != 4 {
		t.Fatalf("expected 4 total system services (NC and socket units excluded), got %d", ping.SystemServices.Total)
	}
	if ping.SystemServices.Active != 4 {
		t.Fatalf("expected 4 active system services, got %d", ping.SystemServices.Active)
	}
}

// TestHTTPListSystemServicesIncludesSystemController verifies the
// systemcontroller itself appears in the system services list when the
// SystemControllerImage field is configured, with the key
// SystemControllerServiceKey and the host unit name.
func TestHTTPListSystemServicesIncludesSystemController(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)
	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemControllerUnitName, ActiveState: "active", SubState: "running"},
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	var sc *SystemServiceEntry
	for i := range entries {
		if entries[i].Key == SystemControllerServiceKey {
			sc = &entries[i]
			break
		}
	}
	if sc == nil {
		t.Fatal("expected systemcontroller entry in system services")
	}
	if sc.DisplayName != "System Controller" {
		t.Fatalf("expected DisplayName 'System Controller', got %q", sc.DisplayName)
	}
	if sc.Image != "quay.io/town/town:test" {
		t.Fatalf("expected image 'quay.io/town/town:test', got %q", sc.Image)
	}
	if sc.Port != "5309" {
		t.Fatalf("expected port '5309', got %q", sc.Port)
	}
	if sc.Name != systemd.SystemControllerUnitName {
		t.Fatalf("expected unit name %q, got %q", systemd.SystemControllerUnitName, sc.Name)
	}
	if sc.ActiveState != "active" {
		t.Fatalf("expected ActiveState 'active', got %q", sc.ActiveState)
	}
}

// TestHTTPListSystemServicesOmitsSystemControllerWhenUnconfigured verifies
// that the systemcontroller is NOT listed when ServerConfig does not
// set SystemControllerImage. Tests that don't care about the self entry
// should see empty or monitoring-only results.
func TestHTTPListSystemServicesOmitsSystemControllerWhenUnconfigured(t *testing.T) {
	mock := storage.InitBtrFSMock()
	sd := systemd.InitMockManager()
	ts := InitTestServer(ServerConfig{
		Storage:           mock,
		Systemd:           sd,
		MonitoringBackend: monitoring.BackendUPlot,
		// Deliberately leave SystemControllerImage unset.
	})
	t.Cleanup(ts.Close)

	c, err := ts.Client()
	if err != nil {
		t.Fatalf("ts.Client: %v", err)
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	for _, e := range entries {
		if e.Key == SystemControllerServiceKey {
			t.Fatalf("expected no systemcontroller entry when image unset, got %+v", e)
		}
	}
	// Monitoring-only count: node-exporter, prometheus, monitoring-ui.
	if len(entries) != 3 {
		t.Fatalf("expected 3 entries (no systemcontroller), got %d", len(entries))
	}
}

// TestHTTPSetSystemServiceStatusSystemControllerStopRejected verifies
// that stopping the systemcontroller via the system services API is
// rejected — it would kill the very process handling the request.
func TestHTTPSetSystemServiceStatusSystemControllerStopRejected(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	err := c.SetSystemServiceStatus(context.TODO(), SystemControllerServiceKey, systemd.Stop)
	if err == nil {
		t.Fatal("expected error for stopping systemcontroller")
	}
}

// TestHTTPSetSystemServiceStatusSystemControllerRestartAllowed verifies
// that restart IS permitted for the systemcontroller key — the handler
// schedules the restart in a background goroutine so the HTTP response
// can flush before systemd kills the process.
func TestHTTPSetSystemServiceStatusSystemControllerRestartAllowed(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	if err := c.SetSystemServiceStatus(context.TODO(), SystemControllerServiceKey, systemd.Restart); err != nil {
		t.Fatalf("expected restart to succeed, got error: %v", err)
	}
	// The actual SetStatus call happens in a delayed goroutine; we only
	// assert the handler accepted the request (200 OK, no error).
}

// TestExtractListenPort pins the listen-address parsing used by the
// systemcontroller self entry so display values stay stable across
// refactors.
func TestExtractListenPort(t *testing.T) {
	cases := []struct {
		addr string
		want string
	}{
		{":5309", "5309"},
		{"0.0.0.0:5309", "5309"},
		{"127.0.0.1:8080", "8080"},
		{"[::1]:5309", "5309"},
		{"", ""},
		{"no-colon", ""},
	}
	for _, tc := range cases {
		if got := extractListenPort(tc.addr); got != tc.want {
			t.Errorf("extractListenPort(%q) = %q, want %q", tc.addr, got, tc.want)
		}
	}
}

func TestMockClientListSystemServices(t *testing.T) {
	m := InitMockClient()
	m.SystemServices = []SystemServiceEntry{
		{Key: "node-exporter", DisplayName: "Node Exporter"},
	}

	entries, err := m.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(entries))
	}

	if entries[0].Key != "node-exporter" {
		t.Fatalf("expected key node-exporter, got %q", entries[0].Key)
	}
}

func TestMockClientListSystemServicesError(t *testing.T) {
	m := InitMockClient()
	m.ListSystemServicesErr = errors.New("injected")

	_, err := m.ListSystemServices(context.TODO())
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestMockClientSetSystemServiceStatus(t *testing.T) {
	m := InitMockClient()

	if err := m.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Start); err != nil {
		t.Fatalf("SetSystemServiceStatus: %v", err)
	}

	calls := m.GetCalls()
	if len(calls) != 1 {
		t.Fatalf("expected 1 call, got %d", len(calls))
	}
	if calls[0].Method != "SetSystemServiceStatus" {
		t.Fatalf("expected method SetSystemServiceStatus, got %q", calls[0].Method)
	}
}

func TestMockClientSetSystemServiceStatusRejectsEnable(t *testing.T) {
	m := InitMockClient()

	err := m.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Enable)
	if err == nil {
		t.Fatal("expected error for enable action")
	}
}
