// IRON RULE: make test-full must always be able to run simultaneously in the
// same repository without conflicting. Nothing else matters more than this.

package systemcontroller

import (
	"context"
	"errors"
	"testing"

	"gitea.com/town-os/town-os/src/monitoring"
	"gitea.com/town-os/town-os/src/storage"
	"gitea.com/town-os/town-os/src/systemd"
)

func initSystemServiceTestClient(t *testing.T) (*SystemdClient, *systemd.MockManager) {
	t.Helper()
	mock := storage.InitBtrFSMock()
	sd := systemd.InitMockManager()

	ts := InitTestServer(ServerConfig{
		Storage:           mock,
		Systemd:           sd,
		MonitoringBackend: monitoring.BackendUPlot,
	})
	t.Cleanup(ts.Close)

	c, err := ts.Client()
	if err != nil {
		t.Fatalf("ts.Client: %v", err)
	}

	return c, sd
}

func TestHTTPListSystemServicesWithoutMonitoring(t *testing.T) {
	mock := storage.InitBtrFSMock()
	ts := InitTestServer(ServerConfig{Storage: mock})
	t.Cleanup(ts.Close)

	c, err := ts.Client()
	if err != nil {
		t.Fatalf("ts.Client: %v", err)
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 0 {
		t.Fatalf("expected 0 entries without monitoring, got %d", len(entries))
	}
}

func TestHTTPListSystemServicesWithMonitoring(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	// All monitoring services: node-exporter, prometheus, monitoring-ui.
	if len(entries) != 3 {
		t.Fatalf("expected 3 entries (node-exporter, prometheus, monitoring-ui), got %d", len(entries))
	}

	keys := map[string]bool{}
	for _, e := range entries {
		keys[e.Key] = true
		if e.Image == "" {
			t.Fatalf("expected non-empty image for %s", e.Key)
		}
		if e.Port == "" {
			t.Fatalf("expected non-empty port for %s", e.Key)
		}
		if e.DisplayName == "" {
			t.Fatalf("expected non-empty display name for %s", e.Key)
		}
	}

	for _, expected := range []string{"node-exporter", "prometheus", "monitoring-ui"} {
		if !keys[expected] {
			t.Fatalf("expected key %q in system services", expected)
		}
	}
}

func TestHTTPListSystemServicesReportsRunningState(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active", SubState: "running"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active", SubState: "running"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active", SubState: "running"},
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 3 {
		t.Fatalf("expected 3 entries, got %d", len(entries))
	}

	for _, e := range entries {
		if e.ActiveState != "active" {
			t.Fatalf("expected %s active, got %q", e.Key, e.ActiveState)
		}
	}
}

// TestHTTPListSystemServicesIgnoresNCAndSocketUnits verifies that system
// service NC and socket units (generated by the package unit path for
// monitoring services) are not returned as separate entries from
// ListSystemServices — only the three main service entries are returned.
func TestHTTPListSystemServicesIgnoresNCAndSocketUnits(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active"},
		{Name: "town-os-system--prometheus-network.service", ActiveState: "active"},
		{Name: "town-os-system--prometheus-9090-tcp.socket", ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-network.service", ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-5308-tcp.socket", ActiveState: "active"},
	}

	entries, err := c.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 3 {
		t.Fatalf("expected 3 entries (NC and socket units excluded), got %d", len(entries))
	}
	for _, e := range entries {
		if e.Key != "node-exporter" && e.Key != "prometheus" && e.Key != "monitoring-ui" {
			t.Fatalf("unexpected entry key %q", e.Key)
		}
	}
}

func TestHTTPSetSystemServiceStatusStart(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	if err := c.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Start); err != nil {
		t.Fatalf("SetSystemServiceStatus: %v", err)
	}

	calls := sd.GetCalls()
	found := false
	for _, call := range calls {
		if call.Method == "SetStatus" && len(call.Args) >= 2 {
			if call.Args[0] == systemd.SystemServiceUnitName("node-exporter") && call.Args[1] == systemd.Start {
				found = true
			}
		}
	}
	if !found {
		t.Fatal("expected SetStatus(node-exporter, start) call")
	}
}

func TestHTTPSetSystemServiceStatusRestart(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	if err := c.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Restart); err != nil {
		t.Fatalf("SetSystemServiceStatus: %v", err)
	}
}

func TestHTTPSetSystemServiceStatusEnableRejected(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	err := c.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Enable)
	if err == nil {
		t.Fatal("expected error for enable action")
	}
}

func TestHTTPSetSystemServiceStatusInvalidKey(t *testing.T) {
	c, _ := initSystemServiceTestClient(t)

	err := c.SetSystemServiceStatus(context.TODO(), "nonexistent", systemd.Start)
	if err == nil {
		t.Fatal("expected error for invalid key")
	}
}

func TestHTTPPingIncludesSystemServiceCounts(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active"},
	}

	ping, err := c.Ping(context.TODO())
	if err != nil {
		t.Fatalf("Ping: %v", err)
	}

	if ping.SystemServices == nil {
		t.Fatal("expected system_services in ping response")
	}

	if ping.SystemServices.Total != 3 {
		t.Fatalf("expected 3 total system services, got %d", ping.SystemServices.Total)
	}

	if ping.SystemServices.Active != 3 {
		t.Fatalf("expected 3 active system services, got %d", ping.SystemServices.Active)
	}
}

// TestHTTPPingExcludesSystemServiceNCAndSocketUnits verifies that network
// controller and socket units generated for system services (via the package
// unit path for prometheus, monitoring-ui, etc.) are not counted in the
// system_services total — only the main service units are.
func TestHTTPPingExcludesSystemServiceNCAndSocketUnits(t *testing.T) {
	c, sd := initSystemServiceTestClient(t)

	sd.Units = []systemd.UnitStatus{
		{Name: systemd.SystemServiceUnitName("node-exporter"), ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("prometheus"), ActiveState: "active"},
		{Name: "town-os-system--prometheus-network.service", ActiveState: "active"},
		{Name: "town-os-system--prometheus-9090-tcp.socket", ActiveState: "active"},
		{Name: systemd.SystemServiceUnitName("monitoring-ui"), ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-network.service", ActiveState: "active"},
		{Name: "town-os-system--monitoring-ui-5308-tcp.socket", ActiveState: "active"},
	}

	ping, err := c.Ping(context.TODO())
	if err != nil {
		t.Fatalf("Ping: %v", err)
	}

	if ping.SystemServices == nil {
		t.Fatal("expected system_services in ping response")
	}

	// Only node-exporter, prometheus, monitoring-ui count — not NC or sockets.
	if ping.SystemServices.Total != 3 {
		t.Fatalf("expected 3 total system services (NC and socket units excluded), got %d", ping.SystemServices.Total)
	}
	if ping.SystemServices.Active != 3 {
		t.Fatalf("expected 3 active system services, got %d", ping.SystemServices.Active)
	}
}

func TestMockClientListSystemServices(t *testing.T) {
	m := InitMockClient()
	m.SystemServices = []SystemServiceEntry{
		{Key: "node-exporter", DisplayName: "Node Exporter"},
	}

	entries, err := m.ListSystemServices(context.TODO())
	if err != nil {
		t.Fatalf("ListSystemServices: %v", err)
	}

	if len(entries) != 1 {
		t.Fatalf("expected 1 entry, got %d", len(entries))
	}

	if entries[0].Key != "node-exporter" {
		t.Fatalf("expected key node-exporter, got %q", entries[0].Key)
	}
}

func TestMockClientListSystemServicesError(t *testing.T) {
	m := InitMockClient()
	m.ListSystemServicesErr = errors.New("injected")

	_, err := m.ListSystemServices(context.TODO())
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestMockClientSetSystemServiceStatus(t *testing.T) {
	m := InitMockClient()

	if err := m.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Start); err != nil {
		t.Fatalf("SetSystemServiceStatus: %v", err)
	}

	calls := m.GetCalls()
	if len(calls) != 1 {
		t.Fatalf("expected 1 call, got %d", len(calls))
	}
	if calls[0].Method != "SetSystemServiceStatus" {
		t.Fatalf("expected method SetSystemServiceStatus, got %q", calls[0].Method)
	}
}

func TestMockClientSetSystemServiceStatusRejectsEnable(t *testing.T) {
	m := InitMockClient()

	err := m.SetSystemServiceStatus(context.TODO(), "node-exporter", systemd.Enable)
	if err == nil {
		t.Fatal("expected error for enable action")
	}
}
