package systemcontroller

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os/exec"
	"strings"
	"time"
)

// ContainerExecFunc runs a shell command inside a running container and
// returns its combined output. It is the single injection point for every
// `podman exec` the install and reconcile paths make, so tests can drive the
// post-install machinery without podman, a container, or root.
type ContainerExecFunc func(ctx context.Context, containerName, command string) (string, error)

const (
	// containerExecTimeout bounds a single command. Post-install work is
	// API calls against a sibling service, not a migration, but the same
	// ceiling as post_update is used so one wedged command cannot hold an
	// install request open forever.
	containerExecTimeout = 5 * time.Minute

	// postInstallReadyTimeout bounds the wait for the container to accept an
	// exec at all. systemd's StartUnit job reports "done" once podman run has
	// been launched, which is strictly earlier than the container being able
	// to serve an exec, so the first command would otherwise race the start.
	postInstallReadyTimeout = 90 * time.Second

	// postInstallReadyInterval is the poll gap while waiting for that.
	postInstallReadyInterval = 2 * time.Second
)

// errContainerNeverReady reports that the container did not accept an exec
// within postInstallReadyTimeout. Callers log it and move on: the package is
// installed and running either way, and failing the install here would not
// undo anything already on disk.
var errContainerNeverReady = errors.New("container did not become ready for exec")

// PodmanContainerExec is the production ContainerExecFunc: it runs the command
// through `sh -c` inside the named container. Exported so the boot path can
// reuse it for post_update rather than keeping a second copy of the same
// invocation.
func PodmanContainerExec(ctx context.Context, containerName, command string) (string, error) {
	execCtx, cancel := context.WithTimeout(ctx, containerExecTimeout)
	defer cancel()

	out, err := exec.CommandContext(execCtx, "podman", "exec", containerName, "sh", "-c", command).CombinedOutput() //nolint:gosec // G204 -- containerName is generated by systemd.ContainerName and command comes from trusted package YAML, control-char-swept at compile time
	if err != nil {
		return string(out), fmt.Errorf("%w: %s", err, string(out))
	}
	return string(out), nil
}

// waitContainerReady polls until the container accepts an exec, or the timeout
// elapses. The probe is `true` — the cheapest command that still proves the
// whole path works: the container exists, is running, and has a shell to run
// post_install commands with. An image without /bin/sh fails here rather than
// halfway through the operator's command list.
func waitContainerReady(ctx context.Context, execFn ContainerExecFunc, containerName string, timeout, interval time.Duration) error {
	if execFn == nil {
		return errors.New("no container exec function configured")
	}

	deadline := time.Now().Add(timeout)
	var lastErr error
	for {
		_, err := execFn(ctx, containerName, "true")
		if err == nil {
			return nil
		}
		lastErr = err
		if !time.Now().Before(deadline) {
			return fmt.Errorf("%w: %s after %s: %w", errContainerNeverReady, containerName, timeout, lastErr)
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(interval):
		}
	}
}

// runPostInstall executes a package's post_install commands inside its
// container, in declaration order, after waiting for the container to accept
// an exec.
//
// Every failure is logged and swallowed rather than returned, and the choice
// is deliberate on both halves:
//
//   - Swallowed, because by the time this runs the package is fully installed
//     — volumes provisioned, install record saved, units on disk and started.
//     There is nothing left to roll back, so failing the request would report
//     a failure for an install that in fact happened, and (for a dependency)
//     would abort the parent's install over a wiring step that is by
//     definition supplementary to it.
//   - Logged at Warn, because the commands exist precisely to configure what a
//     bind mount cannot, so a silent skip leaves a stack that looks installed
//     and is not wired. The journal is where that becomes visible.
//
// Commands must be idempotent: an install of a new version over an old one
// runs them again, and so does a reinstall over reused volumes.
//
// readyTimeout and readyInterval bound the wait for the container. They are
// parameters rather than reads of the constants so a test can prove the
// never-ready path without spending postInstallReadyTimeout doing it;
// production call sites pass the constants.
func runPostInstall(ctx context.Context, execFn ContainerExecFunc, containerName string, commands []string, readyTimeout, readyInterval time.Duration) {
	if len(commands) == 0 {
		return
	}
	if execFn == nil {
		slog.Warn("post-install skipped: no container exec function configured", "container", containerName)
		return
	}

	if err := waitContainerReady(ctx, execFn, containerName, readyTimeout, readyInterval); err != nil {
		slog.Warn("post-install skipped", "container", containerName, "error", err)
		return
	}

	for idx, cmd := range commands {
		out, err := execFn(ctx, containerName, cmd)
		if err != nil {
			slog.Warn("post-install command failed", "container", containerName, "index", idx, "command", cmd, "error", err)
			continue
		}
		if trimmed := strings.TrimSpace(out); trimmed != "" {
			slog.Info("post-install", "container", containerName, "index", idx, "output", trimmed)
		}
	}
}

// postInstallCommands merges a dependency's own top-level post_install list
// with the list its parent injected via `dependencies.<key>.post_install:`.
// The dep's own commands run first: they configure the package as its author
// intended, and the parent's injections wire that configured package to its
// siblings.
//
// The result is always a fresh slice, never an alias of either argument:
// callers hand it to applyDepTemplatesSlice, which rewrites entries in place,
// and that must not reach back into the compiled package's own PostInstall.
func postInstallCommands(own, injected []string) []string {
	if len(own)+len(injected) == 0 {
		return nil
	}
	merged := make([]string, 0, len(own)+len(injected))
	merged = append(merged, own...)
	merged = append(merged, injected...)
	return merged
}
