package rolodex

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeResolvConf(t *testing.T, name, content string) string {
	t.Helper()

	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return path
}

func TestParseResolvConfExtractsNameservers(t *testing.T) {
	t.Parallel()

	got := parseResolvConf([]byte(`# Generated by whatever
search lan
nameserver 192.168.1.1
nameserver 10.0.0.53
options edns0
`))

	want := []string{"192.168.1.1:53", "10.0.0.53:53"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("parseResolvConf = %v, want %v", got, want)
	}
}

// A loopback nameserver is what systemd-resolved's stub (127.0.0.53) and
// rolodex's own listener (127.0.0.2) look like. Forwarding to either sends the
// query straight back to the resolver that asked it, so both must be discarded
// — and discarding them is what makes /etc/resolv.conf on a resolved box yield
// nothing, which is why the uplink file is consulted first.
func TestParseResolvConfDropsLoopbackAndUnroutableAddresses(t *testing.T) {
	t.Parallel()

	got := parseResolvConf([]byte(`nameserver 127.0.0.53
nameserver 127.0.0.2
nameserver ::1
nameserver 0.0.0.0
nameserver 224.0.0.251
nameserver fe80::1
nameserver not-an-ip
nameserver
`))

	if len(got) != 0 {
		t.Fatalf("parseResolvConf = %v, want none of these to be usable", got)
	}
}

func TestParseResolvConfKeepsIPv6AndDeduplicates(t *testing.T) {
	t.Parallel()

	got := parseResolvConf([]byte(`nameserver 2001:4860:4860::8888
nameserver 192.168.1.1
nameserver 192.168.1.1
`))

	want := []string{"[2001:4860:4860::8888]:53", "192.168.1.1:53"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("parseResolvConf = %v, want %v", got, want)
	}
}

func TestParseResolvConfHonoursComments(t *testing.T) {
	t.Parallel()

	got := parseResolvConf([]byte(`nameserver 192.168.1.1 # the router
; nameserver 9.9.9.9
# nameserver 8.8.8.8
`))

	want := []string{"192.168.1.1:53"}
	if strings.Join(got, ",") != strings.Join(want, ",") {
		t.Fatalf("parseResolvConf = %v, want %v", got, want)
	}
}

// The first file that yields a usable address wins — not merely the first file
// that exists. On a resolved box /etc/resolv.conf exists and holds only the
// loopback stub, so a discovery that stopped at the first readable file would
// find nothing on exactly the boxes this feature is for.
func TestHostResolversFromFallsThroughAnEmptyFile(t *testing.T) {
	t.Parallel()

	stub := writeResolvConf(t, "stub-resolv.conf", "nameserver 127.0.0.53\n")
	uplink := writeResolvConf(t, "resolv.conf", "nameserver 192.168.7.1\n")

	got := HostResolversFrom(filepath.Join(t.TempDir(), "missing.conf"), stub, uplink)
	if strings.Join(got, ",") != "192.168.7.1:53" {
		t.Fatalf("HostResolversFrom = %v, want [192.168.7.1:53]", got)
	}
}

func TestHostResolversFromReturnsNothingWhenNoFileIsUsable(t *testing.T) {
	t.Parallel()

	stub := writeResolvConf(t, "stub-resolv.conf", "nameserver 127.0.0.53\n")

	if got := HostResolversFrom(stub); len(got) != 0 {
		t.Fatalf("HostResolversFrom = %v, want empty", got)
	}
}

// The system paths are the contract with the systemcontroller unit, which
// bind-mounts /run/systemd precisely so the uplink file is reachable from
// inside the container. Losing either entry — or their order — silently
// degrades discovery to whatever /etc/resolv.conf happens to hold.
func TestHostResolvConfPathsPreferTheResolvedUplinkFile(t *testing.T) {
	t.Parallel()

	want := []string{"/run/systemd/resolve/resolv.conf", "/etc/resolv.conf"}
	if strings.Join(hostResolvConfPaths, ",") != strings.Join(want, ",") {
		t.Fatalf("hostResolvConfPaths = %v, want %v", hostResolvConfPaths, want)
	}
}
