version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - funcorder
    - funlen
    - gochecknoglobals
    - gocognit
    - gocyclo
    - goconst
    - godox
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - misspell
    - mnd
    - nestif
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - prealloc
    - revive
    - tagalign
    - tagliatelle
    - testpackage
    - varnamelen
    - maintidx
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - linters:
          - gosec
        path: _test\.go
