FROM docker.io/library/golang:1.25-bookworm AS builder
COPY go.mod go.sum /src/
WORKDIR /src
RUN go mod download
COPY . /src
RUN CGO_ENABLED=0 go build -o /town-os-networkcontroller ./src/networkcontroller/cmd/town-os-networkcontroller

FROM docker.io/library/alpine:latest
RUN apk add --no-cache socat
COPY --from=builder /town-os-networkcontroller /town-os-networkcontroller
CMD ["/town-os-networkcontroller"]
