FROM docker.io/library/golang:1.25-bookworm AS builder
COPY go.mod go.sum /src/
WORKDIR /src
RUN go mod download
COPY . /src
RUN CGO_ENABLED=0 go build -o /town-os-ingress ./src/ingress/cmd/town-os-ingress

FROM docker.io/library/caddy:2-alpine AS caddy

FROM docker.io/library/alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=caddy /usr/bin/caddy /usr/bin/caddy
COPY --from=builder /town-os-ingress /town-os-ingress
CMD ["/town-os-ingress"]
