// IRON RULE: make test-full must always be able to run simultaneously in the
// same repository without conflicting. Nothing else matters more than this.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: src/ingress/proto/ingress.proto

package ingresspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ingress_SetRoutes_FullMethodName   = "/townos.ingress.v1.Ingress/SetRoutes"
	Ingress_AddRoute_FullMethodName    = "/townos.ingress.v1.Ingress/AddRoute"
	Ingress_RemoveRoute_FullMethodName = "/townos.ingress.v1.Ingress/RemoveRoute"
	Ingress_ListRoutes_FullMethodName  = "/townos.ingress.v1.Ingress/ListRoutes"
)

// IngressClient is the client API for Ingress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Ingress is the management API the systemcontroller uses to program the shared
// :443 SNI ingress. The ingress service holds the desired route set in memory,
// renders a Caddyfile, and reloads its caddy child zero-downtime on every
// change. Programming is push/declarative: on a fresh ingress the
// systemcontroller calls SetRoutes with the full desired state (the same
// resilience model as rolodex RebuildDNS); AddRoute/RemoveRoute give CRUD
// handlers immediate effect without a full resend.
type IngressClient interface {
	// SetRoutes replaces the entire route set with the supplied list (idempotent
	// reconcile). Any host not present is dropped.
	SetRoutes(ctx context.Context, in *SetRoutesRequest, opts ...grpc.CallOption) (*SetRoutesResponse, error)
	// AddRoute upserts a single route keyed by hostname.
	AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteResponse, error)
	// RemoveRoute deletes the route for the given hostname (no error if absent).
	RemoveRoute(ctx context.Context, in *RemoveRouteRequest, opts ...grpc.CallOption) (*RemoveRouteResponse, error)
	// ListRoutes returns the current route set (for debugging and tests).
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
}

type ingressClient struct {
	cc grpc.ClientConnInterface
}

func NewIngressClient(cc grpc.ClientConnInterface) IngressClient {
	return &ingressClient{cc}
}

func (c *ingressClient) SetRoutes(ctx context.Context, in *SetRoutesRequest, opts ...grpc.CallOption) (*SetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRoutesResponse)
	err := c.cc.Invoke(ctx, Ingress_SetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) AddRoute(ctx context.Context, in *AddRouteRequest, opts ...grpc.CallOption) (*AddRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRouteResponse)
	err := c.cc.Invoke(ctx, Ingress_AddRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) RemoveRoute(ctx context.Context, in *RemoveRouteRequest, opts ...grpc.CallOption) (*RemoveRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRouteResponse)
	err := c.cc.Invoke(ctx, Ingress_RemoveRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, Ingress_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngressServer is the server API for Ingress service.
// All implementations must embed UnimplementedIngressServer
// for forward compatibility.
//
// Ingress is the management API the systemcontroller uses to program the shared
// :443 SNI ingress. The ingress service holds the desired route set in memory,
// renders a Caddyfile, and reloads its caddy child zero-downtime on every
// change. Programming is push/declarative: on a fresh ingress the
// systemcontroller calls SetRoutes with the full desired state (the same
// resilience model as rolodex RebuildDNS); AddRoute/RemoveRoute give CRUD
// handlers immediate effect without a full resend.
type IngressServer interface {
	// SetRoutes replaces the entire route set with the supplied list (idempotent
	// reconcile). Any host not present is dropped.
	SetRoutes(context.Context, *SetRoutesRequest) (*SetRoutesResponse, error)
	// AddRoute upserts a single route keyed by hostname.
	AddRoute(context.Context, *AddRouteRequest) (*AddRouteResponse, error)
	// RemoveRoute deletes the route for the given hostname (no error if absent).
	RemoveRoute(context.Context, *RemoveRouteRequest) (*RemoveRouteResponse, error)
	// ListRoutes returns the current route set (for debugging and tests).
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	mustEmbedUnimplementedIngressServer()
}

// UnimplementedIngressServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngressServer struct{}

func (UnimplementedIngressServer) SetRoutes(context.Context, *SetRoutesRequest) (*SetRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRoutes not implemented")
}
func (UnimplementedIngressServer) AddRoute(context.Context, *AddRouteRequest) (*AddRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRoute not implemented")
}
func (UnimplementedIngressServer) RemoveRoute(context.Context, *RemoveRouteRequest) (*RemoveRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRoute not implemented")
}
func (UnimplementedIngressServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedIngressServer) mustEmbedUnimplementedIngressServer() {}
func (UnimplementedIngressServer) testEmbeddedByValue()                 {}

// UnsafeIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngressServer will
// result in compilation errors.
type UnsafeIngressServer interface {
	mustEmbedUnimplementedIngressServer()
}

func RegisterIngressServer(s grpc.ServiceRegistrar, srv IngressServer) {
	// If the following call panics, it indicates UnimplementedIngressServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ingress_ServiceDesc, srv)
}

func _Ingress_SetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).SetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_SetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).SetRoutes(ctx, req.(*SetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_AddRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).AddRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_AddRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).AddRoute(ctx, req.(*AddRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_RemoveRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).RemoveRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_RemoveRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).RemoveRoute(ctx, req.(*RemoveRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ingress_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ingress_ServiceDesc is the grpc.ServiceDesc for Ingress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "townos.ingress.v1.Ingress",
	HandlerType: (*IngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRoutes",
			Handler:    _Ingress_SetRoutes_Handler,
		},
		{
			MethodName: "AddRoute",
			Handler:    _Ingress_AddRoute_Handler,
		},
		{
			MethodName: "RemoveRoute",
			Handler:    _Ingress_RemoveRoute_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _Ingress_ListRoutes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/ingress/proto/ingress.proto",
}
