// IRON RULE: make test-full must always be able to run simultaneously in the
// same repository without conflicting. Nothing else matters more than this.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: src/ingress/proto/ingress.proto

package ingresspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Route is one https vhost the ingress terminates and reverse-proxies. It maps
// 1:1 to the systemcontroller's PackageIngressSite.
type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SNI host the vhost is keyed by (e.g. "gitea.asdf.home").
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// reverse_proxy target as "container:port" on the ingress network.
	Backend string `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	// Directory containing cert.pem + key.pem (a file-pinned local-CA leaf).
	// Empty when acme is true.
	CertDir string `protobuf:"bytes,3,opt,name=cert_dir,json=certDir,proto3" json:"cert_dir,omitempty"`
	// When true the cert is obtained via an ACME issuer instead of cert_dir.
	Acme bool `protobuf:"varint,4,opt,name=acme,proto3" json:"acme,omitempty"`
	// When true the backend speaks HTTPS: proxy over https and skip verification
	// on the internal hop (the browser still validates the ingress leaf).
	BackendTls bool `protobuf:"varint,5,opt,name=backend_tls,json=backendTls,proto3" json:"backend_tls,omitempty"`
	// When true the ingress also serves this route over plain HTTP on :80,
	// reverse-proxying to the backend (used for static pages, which carry
	// nothing sensitive). When false (the default, used by packages) the :80
	// vhost is an HTTP->HTTPS redirect so the route stays HTTPS-only.
	ServeHttp bool `protobuf:"varint,6,opt,name=serve_http,json=serveHttp,proto3" json:"serve_http,omitempty"`
	// Paths that go somewhere other than backend. Empty for almost every route:
	// one vhost, one service, is the norm.
	//
	// It exists because a backend can own a name without owning every path under
	// it. gfeh's http view answers exactly /f/<token> and 404s its own root, so
	// the object-storage index is served at "/" by the pages container while
	// every published link still reaches gfehd (see gfehIngressRoutes).
	PathBackends  []*PathBackend `protobuf:"bytes,7,rep,name=path_backends,json=pathBackends,proto3" json:"path_backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Route) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Route) GetCertDir() string {
	if x != nil {
		return x.CertDir
	}
	return ""
}

func (x *Route) GetAcme() bool {
	if x != nil {
		return x.Acme
	}
	return false
}

func (x *Route) GetBackendTls() bool {
	if x != nil {
		return x.BackendTls
	}
	return false
}

func (x *Route) GetServeHttp() bool {
	if x != nil {
		return x.ServeHttp
	}
	return false
}

func (x *Route) GetPathBackends() []*PathBackend {
	if x != nil {
		return x.PathBackends
	}
	return nil
}

// PathBackend sends one path of a route somewhere other than the route's own
// backend.
type PathBackend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caddy path matcher: "/" matches the root and nothing else, "/f/*" matches
	// a prefix. Rendered into a `handle` block, so it must be a path and nothing
	// more — the ingress drops one that is not.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// reverse_proxy target as "container:port" on the ingress network.
	Backend       string `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathBackend) Reset() {
	*x = PathBackend{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathBackend) ProtoMessage() {}

func (x *PathBackend) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathBackend.ProtoReflect.Descriptor instead.
func (*PathBackend) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{1}
}

func (x *PathBackend) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathBackend) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type SetRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoutesRequest) Reset() {
	*x = SetRoutesRequest{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoutesRequest) ProtoMessage() {}

func (x *SetRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoutesRequest.ProtoReflect.Descriptor instead.
func (*SetRoutesRequest) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{2}
}

func (x *SetRoutesRequest) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type SetRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoutesResponse) Reset() {
	*x = SetRoutesResponse{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoutesResponse) ProtoMessage() {}

func (x *SetRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoutesResponse.ProtoReflect.Descriptor instead.
func (*SetRoutesResponse) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{3}
}

type AddRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRouteRequest) Reset() {
	*x = AddRouteRequest{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteRequest) ProtoMessage() {}

func (x *AddRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteRequest.ProtoReflect.Descriptor instead.
func (*AddRouteRequest) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{4}
}

func (x *AddRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type AddRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRouteResponse) Reset() {
	*x = AddRouteResponse{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteResponse) ProtoMessage() {}

func (x *AddRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteResponse.ProtoReflect.Descriptor instead.
func (*AddRouteResponse) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{5}
}

type RemoveRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRouteRequest) Reset() {
	*x = RemoveRouteRequest{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRouteRequest) ProtoMessage() {}

func (x *RemoveRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRouteRequest.ProtoReflect.Descriptor instead.
func (*RemoveRouteRequest) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveRouteRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RemoveRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRouteResponse) Reset() {
	*x = RemoveRouteResponse{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRouteResponse) ProtoMessage() {}

func (x *RemoveRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRouteResponse.ProtoReflect.Descriptor instead.
func (*RemoveRouteResponse) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{7}
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{8}
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_ingress_proto_ingress_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_src_ingress_proto_ingress_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_src_ingress_proto_ingress_proto protoreflect.FileDescriptor

const file_src_ingress_proto_ingress_proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/ingress/proto/ingress.proto\x12\x11townos.ingress.v1\"\xf1\x01\n" +
	"\x05Route\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x19\n" +
	"\bcert_dir\x18\x03 \x01(\tR\acertDir\x12\x12\n" +
	"\x04acme\x18\x04 \x01(\bR\x04acme\x12\x1f\n" +
	"\vbackend_tls\x18\x05 \x01(\bR\n" +
	"backendTls\x12\x1d\n" +
	"\n" +
	"serve_http\x18\x06 \x01(\bR\tserveHttp\x12C\n" +
	"\rpath_backends\x18\a \x03(\v2\x1e.townos.ingress.v1.PathBackendR\fpathBackends\";\n" +
	"\vPathBackend\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\"D\n" +
	"\x10SetRoutesRequest\x120\n" +
	"\x06routes\x18\x01 \x03(\v2\x18.townos.ingress.v1.RouteR\x06routes\"\x13\n" +
	"\x11SetRoutesResponse\"A\n" +
	"\x0fAddRouteRequest\x12.\n" +
	"\x05route\x18\x01 \x01(\v2\x18.townos.ingress.v1.RouteR\x05route\"\x12\n" +
	"\x10AddRouteResponse\"0\n" +
	"\x12RemoveRouteRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x15\n" +
	"\x13RemoveRouteResponse\"\x13\n" +
	"\x11ListRoutesRequest\"F\n" +
	"\x12ListRoutesResponse\x120\n" +
	"\x06routes\x18\x01 \x03(\v2\x18.townos.ingress.v1.RouteR\x06routes2\xef\x02\n" +
	"\aIngress\x12V\n" +
	"\tSetRoutes\x12#.townos.ingress.v1.SetRoutesRequest\x1a$.townos.ingress.v1.SetRoutesResponse\x12S\n" +
	"\bAddRoute\x12\".townos.ingress.v1.AddRouteRequest\x1a#.townos.ingress.v1.AddRouteResponse\x12\\\n" +
	"\vRemoveRoute\x12%.townos.ingress.v1.RemoveRouteRequest\x1a&.townos.ingress.v1.RemoveRouteResponse\x12Y\n" +
	"\n" +
	"ListRoutes\x12$.townos.ingress.v1.ListRoutesRequest\x1a%.townos.ingress.v1.ListRoutesResponseB7Z5gitea.com/town-os/town-os/src/ingress/proto;ingresspbb\x06proto3"

var (
	file_src_ingress_proto_ingress_proto_rawDescOnce sync.Once
	file_src_ingress_proto_ingress_proto_rawDescData []byte
)

func file_src_ingress_proto_ingress_proto_rawDescGZIP() []byte {
	file_src_ingress_proto_ingress_proto_rawDescOnce.Do(func() {
		file_src_ingress_proto_ingress_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_ingress_proto_ingress_proto_rawDesc), len(file_src_ingress_proto_ingress_proto_rawDesc)))
	})
	return file_src_ingress_proto_ingress_proto_rawDescData
}

var file_src_ingress_proto_ingress_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_src_ingress_proto_ingress_proto_goTypes = []any{
	(*Route)(nil),               // 0: townos.ingress.v1.Route
	(*PathBackend)(nil),         // 1: townos.ingress.v1.PathBackend
	(*SetRoutesRequest)(nil),    // 2: townos.ingress.v1.SetRoutesRequest
	(*SetRoutesResponse)(nil),   // 3: townos.ingress.v1.SetRoutesResponse
	(*AddRouteRequest)(nil),     // 4: townos.ingress.v1.AddRouteRequest
	(*AddRouteResponse)(nil),    // 5: townos.ingress.v1.AddRouteResponse
	(*RemoveRouteRequest)(nil),  // 6: townos.ingress.v1.RemoveRouteRequest
	(*RemoveRouteResponse)(nil), // 7: townos.ingress.v1.RemoveRouteResponse
	(*ListRoutesRequest)(nil),   // 8: townos.ingress.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),  // 9: townos.ingress.v1.ListRoutesResponse
}
var file_src_ingress_proto_ingress_proto_depIdxs = []int32{
	1, // 0: townos.ingress.v1.Route.path_backends:type_name -> townos.ingress.v1.PathBackend
	0, // 1: townos.ingress.v1.SetRoutesRequest.routes:type_name -> townos.ingress.v1.Route
	0, // 2: townos.ingress.v1.AddRouteRequest.route:type_name -> townos.ingress.v1.Route
	0, // 3: townos.ingress.v1.ListRoutesResponse.routes:type_name -> townos.ingress.v1.Route
	2, // 4: townos.ingress.v1.Ingress.SetRoutes:input_type -> townos.ingress.v1.SetRoutesRequest
	4, // 5: townos.ingress.v1.Ingress.AddRoute:input_type -> townos.ingress.v1.AddRouteRequest
	6, // 6: townos.ingress.v1.Ingress.RemoveRoute:input_type -> townos.ingress.v1.RemoveRouteRequest
	8, // 7: townos.ingress.v1.Ingress.ListRoutes:input_type -> townos.ingress.v1.ListRoutesRequest
	3, // 8: townos.ingress.v1.Ingress.SetRoutes:output_type -> townos.ingress.v1.SetRoutesResponse
	5, // 9: townos.ingress.v1.Ingress.AddRoute:output_type -> townos.ingress.v1.AddRouteResponse
	7, // 10: townos.ingress.v1.Ingress.RemoveRoute:output_type -> townos.ingress.v1.RemoveRouteResponse
	9, // 11: townos.ingress.v1.Ingress.ListRoutes:output_type -> townos.ingress.v1.ListRoutesResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_ingress_proto_ingress_proto_init() }
func file_src_ingress_proto_ingress_proto_init() {
	if File_src_ingress_proto_ingress_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_ingress_proto_ingress_proto_rawDesc), len(file_src_ingress_proto_ingress_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_ingress_proto_ingress_proto_goTypes,
		DependencyIndexes: file_src_ingress_proto_ingress_proto_depIdxs,
		MessageInfos:      file_src_ingress_proto_ingress_proto_msgTypes,
	}.Build()
	File_src_ingress_proto_ingress_proto = out.File
	file_src_ingress_proto_ingress_proto_goTypes = nil
	file_src_ingress_proto_ingress_proto_depIdxs = nil
}
