FROM debian:bookworm-slim AS runtime-deps
RUN apt-get update && apt-get install -y \
    btrfs-progs libsystemd0 podman runc socat \
    systemd systemd-sysv dbus curl git iptables \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN printf '[engine]\nruntime = "runc"\n' > /etc/containers/containers.conf

FROM runtime-deps
COPY --from=town-os /systemcontroller /systemcontroller
COPY --from=town-os /town-os-networkcontroller /town-os-networkcontroller
COPY --from=town-os /ui /ui
COPY integration/testdata/town-os-systemcontroller.service /etc/systemd/system/
RUN systemctl enable town-os-systemcontroller.service
RUN mkdir -p /data/btrfs /data/repos /data/db /var/run/town-os
EXPOSE 5309
CMD ["/lib/systemd/systemd"]
